### ISSUE TITLE
Is it faster than PSMC ? 

### ISSUE THREAD

**Issue by ZhengJIN94** [emmanuelparadis/psmcr#1]
Hello, 

The package is so brilliant. 
However, how about the speed ? 
Under the same parameters and input file, is this package faster than original PSMC ?

Thank you !
Zheng JIN

**Comment by emmanuelparadis** [comment]
Hi, Thank you for the appreciation.
I don't expect it to be faster or slower than the original PSMC because the C code (which does most of the computation) is (almost) identical to the original code. That said, benchmarks will be welcome if someone runs some :)
Cheers,
Emmanuel
