### ISSUE TITLE
Some sequences shorter than 'trunksize'

### ISSUE THREAD

**Issue by Jenislq90146** [emmanuelparadis/psmcr#10]
Hi Emmanuel,

As a beginner trying to learn about PSMC analysis, I appreciate the R package and help page that makes it easy. However, I have run into this warning message: " In psmc(y, niters = 20, B = 50, mc.cores = 4): some sequences shorter than 'trunksize' ". Also when I run str (psmc output), I found NANs in $ logLik and $ RI. 

below is the code that I am using:

### Fasta file downloaded from this url: https://www.ncbi.nlm.nih.gov/data-hub/genome/?taxon=9627

x <- read.FASTA("GCF_003160815.1_VulVul2.2_genomic.fna") 

y <- seqBinning(x , bin.size = 100) ## saved as "v_vulpes_seqData.rds"

o <- psmc (y, niters = 20, B = 50, mc.cores = 4)

str (o)

output:

List of 12

 $ niters        : num 20

 $ n             : num 23

 $ n_free_lambdas: int 7

 $ logLik        : num [1:21] 0 NaN NaN NaN NaN NaN NaN NaN NaN NaN ...

 $ EMQ           : num [1:21, 1:2] 0e+00 -1e+300 -1e+300 -1e+300 -1e+300 ...

  ..- attr(*, "dimnames")=List of 2

  .. ..$ : NULL

  .. ..$ : chr [1:2] "before" "after"

 $ RI            : num [1:21] NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN ...

 $ Cpi           : num [1:21] 1 1 1 1 1 1 1 1 1 1 ...

 $ Nrecomb       : num [1:21] 0 0 0 0 0 0 0 0 0 0 ...

 $ parameters    : num [1:21, 1:3] 0 0 0 0 0 0 0 0 0 0 ...

  ..- attr(*, "dimnames")=List of 2

  .. ..$ : NULL

  .. ..$ : chr [1:3] "theta0" "rho0" "maxT"

 $ RS            : num [1:483, 1:7] 0 1 2 3 4 5 6 7 8 9 ...

  ..- attr(*, "dimnames")=List of 2

  .. ..$ : NULL

  .. ..$ : chr [1:7] "k" "t_k" "lambda_k" "pi_k" ...

 $ TC            : num[0 , 1:4] 

 $ bootstrap     :List of 3

  ..$ theta0: num [1:50] 0 0 0 0 0 0 0 0 0 0 ...

  ..$ tk    : num [1:23, 1:50] 0 0.0256 0.0578 0.0982 0.149 ...

  ..$ lk    : num [1:23, 1:50] 1 1 1 1 1 1 1 1 1 1 ...

 - attr(*, "class")= chr "psmc"

Where am I making a mistake? Could you please point it out to me? 

Thanks
Jenis Patel

**Comment by emmanuelparadis** [comment]
I had a (very) quick look at your problem. Maybe this comes from the level of assembly of the reference genome which is too "rough", so that there too many scaffolds and/or contigs left. Hence 'trunksize' is longer for these. One solution is to drop these very short sequences from the reference (of course, providing there are long scaffolds which approximate well the real chromosomes).
