### ISSUE TITLE
running the plot.r

### ISSUE THREAD

**Issue by Niloofar-Alaei** [emmanuelparadis/psmcr#4]
Hi, 
I was running the PSMC for different species on the Server, and now I want to plot all of them in one figure and use the different colors for each species. 

It is not possible to use the utils/psmc_plot.pl, then I want to use the R just for plotting. 

Then I have some questions: 
Would you please let me which kind of input I need to run the plots.r? .psmc or .txt or .....

And also, I have a question about how can I install the software?
I used remotes, 

remotes::install_github("emmanuelparadis/psmcr/psmcr"), but it give me this error message:

make: *** [C:/PROGRA~1/R/R-40~1.3/etc/i386/Makeconf:222: Rpsmc.o] Error 1
ERROR: compilation failed for package 'psmcr'
* removing 'C:/Users/Niloofar/Documents/R/win-library/4.0/psmcr'
Error: Failed to install 'psmcr' from GitHub:
(converted from warning) installation of package ‘C:/Users/Niloofar/AppData/Local/Temp/RtmpwTKdBK/file4f641e6e6ecb/psmcr_0.1-2.tar.gz’ had non-zero exit status

Would you please help me to plot my results?

The best 
Niloo

**Comment by emmanuelparadis** [comment]
Hi, You must find local assistance to help solve your problems. These forums are to report issues about the package.
