### ISSUE TITLE
Plotting psmc with previously generated files? 

### ISSUE THREAD

**Issue by cmtom** [emmanuelparadis/psmcr#6]
Hello,

Thank you for developing an R implementation of PSMC! I wish I came across it before I already ran psmc.

I have the same unanswered question as issue #4. I already have run psmc and have .psmc files for hundreds of samples. I was wondering if it is possible to use just the R plotting script in your program, with already generated psmc files, and if so, how could I import the data as a compatible object? Any input would be much appreciated!

Thank you,
Crystal

**Comment by emmanuelparadis** [comment]
Hi. Thank you for your apprecation!
Can you send one of the .psmc files? I'll see if I can write code to import into R.
Cheers

**Comment by cmtom** [comment]
Hi, 

Thank you for your quick response, that would be great! I attached an example. 

[example.psmc.txt](https://github.com/emmanuelparadis/psmcr/files/7468034/example.psmc.txt)
 
Thanks,
Crystal

**Comment by emmanuelparadis** [comment]
I added the function `import.psmc` in the package which is now version 0.1-4. You need to reinstall because it needed to rearrange the code in other functions. Please try it and don't hesitate to give feed-back.
