### ISSUE TITLE
extracting segregating sites data from PSMC run

### ISSUE THREAD

**Issue by sjfleck** [emmanuelparadis/psmcr#8]
Hello,
thank you for this version of PSMC. I'm doing some manipulating of the data (related to the effects of selfing on PSMC plots) and I need information that I'm having trouble extracting from my my PSMCR run. In the original software, one of the output files was .PSMC and it contained some "useful messages" (MM):

MM	Version: 0.6.5-r67
MM	pattern:4+25*2+4+6, n:63, n_free_lambdas:28
MM	n_iterations:25, skip:1, max_t:15, theta/rho:5
MM	is_decoding:0
MM	n_seqs:288, sum_L:22436286, sum_n:2518313

Specifically, I'm interested in "sum_n", the number of segregating sites. I need this for a particular calculation that I need to make, but I'm having trouble identifying where this is in the R variables. 

I'm also trying to find a good way to extract the x and y coordinates for each curve from the PSMCR. I thought I did, but the values don't match the expected Ne on the y-axis and the time on the x-axis. Here's an example of my attempt to plot the data I extracted from PSMCR (I only put 3/100 bootstraps on this plot)
![PSMC_example](https://user-images.githubusercontent.com/53409202/193919845-9fee4822-1de9-4ca3-9e69-469a40c0a809.png)

I would greatly appreciate your advice for extracting the number of segregating sites (sum_n) and the x and y coordinates of the curves so I can manipulate those values. Thank you!

**Comment by emmanuelparadis** [comment]
Hi,
Did you try the option `raw.output = TRUE`? It returns the whole output from PSMC as a bunch of character strings in R. Then you can use `grep()`, `strsplit()`and a few other functions to extract what you need. Maybe something like this:
```r
res <- psmc(........ , raw.output = TRUE)
tmp <- grep("^MM n_seqs:", res, value = TRUE)
tmp <- gsub("^.*sum_n:", "", tmp)
tmp <- as.numeric(tmp)
```
`tmp` should have the value 2518313 according to your example. You can find more examples of this by looking at the code of the internal function:
```r
psmcr:::.extract_psmc
```
The coordinates of the plot are calculated by other internal functions:
```r
psmcr:::.getXYplot.psmc
psmcr:::plot.psmc
```
If you have run PSMC with the above suggested option, you may need to convert the output like this:
```r
res <- psmc(........ , raw.output = TRUE)
cat(res, file = "res.txt")
resPlot <- import.psmc("res.txt")
plot(resPlot) # not plot(res)
```
This will avoid running the complete analysis twice.
Best,

**Comment by sjfleck** [comment]
I haven't tried raw.output = TRUE. Thank you for your advice here and I'll give it a shot today
