### ISSUE TITLE
If the VCF2DNAbin could be used to generate the input sequences for PSMC?

### ISSUE THREAD

**Issue by LanLBio** [emmanuelparadis/psmcr#9]
Hi

I have used the common pipeline and got the  file of vcf.gz, but I could only get empty psmcfa through fq2psmcfa with q=0 or anyother.
So I noticed psmcr, and I use the same input (vcf.gz and the outgroup.fa) and did get the output in R.

7 DNA sequences in binary format stored in a list.
```
Mean sequence length: 41546400
   Shortest sequence: 34303927
    Longest sequence: 50857734

Labels:
Chr06
Chr03
Chr07
Chr05
Chr02
Chr04
...
More than 10 million bases: not printing base composition.
(Total: 290.82 Mb)

```
Here comes the question, as I could not find more detail manual, I have no idea how to do next.
I tried the  write.table(fasta,file="tmp_out") but it didn't work.
If there any ways to get the input for PSMC?

Thanks!
Lan

**Comment by emmanuelparadis** [comment]
Hi,
If your question is how to write the "DNAbin" object into a file, the function `write.FASTA` in ape can do it.
Best,
Emmanuel

**Comment by LanLBio** [comment]
Thanks for you help!
It works!

**Comment by LanLBio** [comment]
Sorry to bother again.
While I tried two different individual vcf file.
And the pipeline is 
```
fasta <- VCF2DNAbin("1.vcf.gz",refgenome = "outgroup.fa")
write.FASTA(fasta,file="1_out")
```
while I got the same size psmc input file.
Also, the sequence shows absolute the same bases with outgroup.fa.
And the the 2.vcf.gz contains only the Chr01, but I also got the total size of the 2_out.

Could you give me some advices?

**Comment by emmanuelparadis** [comment]
That's expected. If the DNA sites from `refgenome` are not in the VCF file, they are returned unchanged. In your case, you may need to select only the chromosome which is in the VCF file, something like:
```r
refgenome <- read.FASTA("outgroup.fa")
names(refgenome)
## the previous command should print the chormosome names
refgenome["Chr01"] # to select the 1st chromosome
fasta1 <- VCF2DNAbin("1.vcf.gz", refgenome = refgenome["Chr01"])
```
You may write a small loop with `paste0` to create file and chromosome names:
```r
for (i in seq_along(refgenome) paste0(i, ".vcf.gz") etc......
```

**Comment by LanLBio** [comment]
Sorry for my late response.
I am testing my pipeline and it works.
Thanks again for your suggestions and help!
